---

nfs_udp: true
nfs_version: 3

memory: 1024

vagrant_provider: 'libvirt'
ip: '192.168.100.100'
puppet_folder: '/opt/puppet-ffm'
hiera_folder: 'hieradata'
hiera_folder_on_guest: '/opt/puppet-ffm/hieradata'

#puppet_options: '--verbose --debug'

boxname: 'trino/ubuntu_14.04.1_lts'
hostname: 'ubuntutrusty'
#boxname: 'trino/debianjessie'
#hostname: 'debianjessie'

