---
dnsmasq::no_hosts: true
dnsmasq::cache_size: 4096

dnsmasq::interfaces:
  - br0

component::fastd::defaults:
  mtu: 1426
  verify_all: true
  log_level: debug2
  methods:
    - salsa2012+umac

component::collectd::plugin_classes:
  - conntrack

component::collectd::plugins:
  dns:
    content: |
      <Plugin dns>
        Interface "br0"
      </Plugin>

component::sysctl::settings:
  fs.file-max:
    value: "100000"
  vm.swappiness:
    value: "10"
  net.ipv4.ip_forward:
    value: "1"
  net.ipv6.conf.all.forwarding:
    value: "1"
  net.ipv6.conf.all.use_tempaddr:
    value: "0"
  net.ipv6.conf.default.use_tempaddr:
    value: "0"
  net.ipv4.conf.default.rp_filter:
    value: "2"
  net.ipv4.conf.all.rp_filter:
    value: "2"
  net.core.default_qdisc:
    value: fq_codel
  # Increase Linux autotuning TCP buffer limits
  # Set max to 16MB for 1GE and 32M (33554432) or 54M (56623104) for 10GE
  # Don't set tcp_mem itself! Let the kernel scale it based on RAM.
  net.core.rmem_max:
    value: "16777216"
  net.core.wmem_max:
    value: "16777216"
  net.core.rmem_default:
    value: "16777216"
  net.core.wmem_default:
    value: "16777216"
  net.core.optmem_max:
    value: "40960"
  net.ipv4.tcp_rmem:
    value: 4096 87380 16777216
  net.ipv4.tcp_wmem:
    value: 4096 65536 16777216
  # Make room for more TIME_WAIT sockets due to more clients,
  # and allow them to be reused if we run out of sockets
  # Also increase the max packet backlog
  net.core.netdev_max_backlog:
    value: "50000"
  net.ipv4.tcp_max_syn_backlog:
    value: "30000"
  net.ipv4.tcp_max_tw_buckets:
    value: "2000000"
  net.ipv4.tcp_tw_reuse:
    value: "1"
  net.ipv4.tcp_fin_timeout:
    value: "10"
  # Increase garbage collection thresholds for neighbor tables
  net.ipv4.neigh.default.gc_thresh1:
    value: "2048"
  net.ipv4.neigh.default.gc_thresh2:
    value: "5120"
  net.ipv4.neigh.default.gc_thresh3:
    value: "10240"
  net.ipv6.neigh.default.gc_thresh1:
    value: "2048"
  net.ipv6.neigh.default.gc_thresh2:
    value: "5120"
  net.ipv6.neigh.default.gc_thresh3:
    value: "10240"
  net.ipv6.route.gc_thresh:
    value: "10240"
  # Disable TCP slow start on idle connections
  net.ipv4.tcp_slow_start_after_idle:
    value: "0"
  # Disable source routing and redirects
  net.ipv4.conf.all.send_redirects:
    value: "0"
  net.ipv4.conf.all.accept_redirects:
    value: "0"
  net.ipv6.conf.all.accept_redirects:
    value: "0"
  net.ipv4.conf.all.accept_source_route:
    value: "0"
  net.ipv6.conf.all.accept_source_route:
    value: "0"
  # Log martian packets
  net.ipv4.conf.all.log_martians:
    value: "1"

